controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

assurance_show:
  path: /assurance/show
  controller: App\Controller\AssuranceController::show

assurance_create:
  path: /assurance/create
  controller: App\Controller\AssuranceController::create

assurance_update:
  path: /assurance/update
  controller: App\Controller\AssuranceController::update

budget:
  path: /budget
  controller: App\Controller\BudgetController::index

budget_show:
  path: /budget/show
  controller: App\Controller\BudgetController::show

budget_create:
  path: /budget/create
  controller: App\Controller\BudgetController::create

budget_update:
  path: /budget/update
  controller: App\Controller\BudgetController::update

carburant_show:
  path: /carburant/show
  controller: App\Controller\CarburantController::show

carburant_create:
  path: /carburant/create
  controller: App\Controller\CarburantController::create

carburant_update:
  path: /carburant/update
  controller: App\Controller\CarburantController::update

departement:
  path: /departement
  controller: App\Controller\DepartementController::index

departement_show:
  path: /departement/show
  controller: App\Controller\DepartementController::show

departement_create:
  path: /departement/create
  controller: App\Controller\DepartementController::create

departement_update:
  path: /departement/update
  controller: App\Controller\DepartementController::update

directeur_commercial_vehicules:
  path: /directeur-commercial/vehicules #auth
  controller: App\Controller\DirecteurCommercialController::viewLimitedVehicules

directeur_commercial_rapport:
  path: /directeur-commercial/rapport #auth
  controller: App\Controller\DirecteurCommercialController::rapport

directeur_commercial_evaluation:
  path: /directeur-commercial/evaluation #auth
  controller: App\Controller\DirecteurCommercialController::efficaciteGestion

directeur_vehicules:
  path: /directeur/vehicules
  controller: App\Controller\DirecteurController::viewAllVehicules

directeur_rapports:
  path: /directeur/rapports #auth
  controller: App\Controller\DirecteurController::rapports

directeur_efficacite:
  path: /directeur/efficacite #auth
  controller: App\Controller\DirecteurController::efficaciteGestion

entretient_index:
  path: /entretient
  controller: App\Controller\EntretientController::index

entretient_show:
  path: /entretient/show
  controller: App\Controller\EntretientController::update

entretient_create:
  path: /entretient/create
  controller: App\Controller\EntretientController::update

entretient_update:
  path: /entretient/update
  controller: App\Controller\EntretientController::update

historique:
  path: /historique
  controller: App\Controller\HistoriqueController::index

historique_show:
  path: /historique/show
  controller: App\Controller\HistoriqueController::update

historique_create:
  path: /historique/create
  controller: App\Controller\HistoriqueController::update

historique_update:
  path: /historique/update
  controller: App\Controller\HistoriqueController::update

vehicule_historique:
  path: /vehicule/historique #auth
  controller: App\Controller\ResponsabledeflotteController::suivreHistoriqueVehicule

vehicule_budget:
  path: /vehicule/budget
  controller: App\Controller\ResponsabledeflotteController::gererBudgetVehicule

#login:
#path: /security/login
#controller: App\Controller\SecurityController::login

utilisateur_index:
  path: /utilisateur
  controller: App\Controller\UtilisateurController::index

utilisateur_new:
  path: /utilisateur/new
  controller: App\Controller\UtilisateurController::new

utilisateur_show:
  path: /utilisateur/show
  controller: App\Controller\UtilisateurController::show

utilisateur_edit:
  path: /utilisateur/edit
  controller: App\Controller\UtilisateurController::edit

vehicule_index:
  path: /vehicules
  controller: App\Controller\VehiculeController::index

vehicule_show:
  path: /vehicules/show
  controller: App\Controller\VehiculeController::show

vehicule_create:
  path: /vehicules/create
  controller: App\Controller\VehiculeController::create

vehicule_update:
  path: /vehicules/update
  controller: App\Controller\VehiculeController::update
